#
# Copyright(c) 2021 ADLINK Technology Limited and others
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
# v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#


trigger: [ '*' ]


variables:
  CIBW_BUILD_VERBOSITY: 0
  CIBW_BEFORE_BUILD: "pip install delvewheel==0.0.12 delocate==0.8.2"
  CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-wheel --wheel_dir {dest_dir} {wheel}"
  CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair --wheel_dir {dest_dir} {wheel}"
  CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --wheel_dir {dest_dir} {wheel}"
  CIBW_SKIP: pp*  # No PyPy builds
  CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_MANYLINUX_I686_IMAGE: manylinux2014
  CIBW_BEFORE_ALL: "git clone https://github.com/eclipse-cyclonedds/cyclonedds.git main && mkdir build install && cd build &&
                    cmake ../main -DCMAKE_INSTALL_PREFIX=../install -DBUILD_IDLC=0 -DBUILD_SCHEMA=0 -DENABLE_SHM=0
                    -DENABLE_TOPIC_DISCOVERY=1 -DENABLE_TYPE_DISCOVERY=1 -DENABLE_SECURITY=0 &&
                    cmake --build . --target install"
  CIBW_ENVIRONMENT_LINUX: "PATH=\"$PATH:/project/install/lib:/project/install/bin\" CYCLONEDDS_HOME=/project/install
                          LIBRARY_PATH=\"$LIBRARY_PATH:/project/install/lib:/project/install/bin\"
                          LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:/project/install/lib:/project/install/bin\""
  CIBW_ENVIRONMENT_WINDOWS: "PATH=\"$PATH:%cd%/install/lib:%cd%/install/bin\" CYCLONEDDS_HOME=%cd%/install"
  CIBW_ENVIRONMENT_MACOS: "PATH=\"$PATH:$(pwd)/install/lib:$(pwd)/install/bin\" CYCLONEDDS_HOME=$(pwd)/install
                           LIBRARY_PATH=\"$LIBRARY_PATH:$(pwd)/install/lib:$(pwd)/install/bin\"
                           LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:$(pwd)/install/lib:$(pwd)/install/bin\""


jobs:
- job: WheelTest
  pool:
    vmImage: $(image)
  strategy:
    matrix:
      'Ubuntu 20.04 LTS':
        image: ubuntu-20.04
      'macOS 10.15':
        image: macOS-10.15
        cc: clang
      'Windows Server 2019':
        image: windows-2019
  steps:
  - template: /.azure/templates/build-wheel.yml