#
# Copyright(c) 2021 ADLINK Technology Limited and others
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
# v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#


trigger: [ '*' ]


variables:
  CIBW_BUILD_VERBOSITY: 1
  CIBW_BEFORE_BUILD: "pip install delvewheel==0.0.12"
  CIBW_REPAIR_WHEEL_COMMAND_LINUX: "delvewheel repair --wheel_dir {dest_dir} {wheel} --add-dll libdds_security_ac.so,libbdds_security_auth.so,libdds_security_crypto.so"
  CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delvewheel repair --wheel_dir {dest_dir} {wheel} --add-dll dds_security_ac.dylib,dds_security_auth.dylib,dds_security_crypto.dylib"
  CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --wheel_dir {dest_dir} {wheel} --add-dll dds_security_ac.dll,dds_security_auth.dll,dds_security_crypto.dll"
  CIBW_SKIP: pp*  # No PyPy builds
  CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_MANYLINUX_I686_IMAGE: manylinux2014
  CIBW_BEFORE_ALL: "git clone https://github.com/eclipse-cyclonedds/cyclonedds.git main && mkdir build install &&
                    cd build && cmake ../main -DCMAKE_INSTALL_PREFIX=../install -DBUILD_IDLC=0 &&
                    cmake --build . --target install"
  CIBW_ENVIRONMENT: "PATH=\"$PATH:$(pwd)/install/lib:$(pwd)/install/bin\" CYCLONEDDS_HOME=$(pwd)/install
                     LIBRARY_PATH=\"$LIBRARY_PATH:$(pwd)/install/lib:$(pwd)/install/bin\"
                     LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:$(pwd)/install/lib:$(pwd)/install/bin\""


jobs:
- job: WheelTest
  pool:
    vmImage: $(image)
  strategy:
    matrix:
      'Ubuntu 20.04 LTS':
        image: ubuntu-20.04
      'macOS 10.15':
        image: macOS-10.15
      'Windows Server 2019':
        image: windows-2019
  steps:
  - template: /.azure/templates/build-wheel.yml